Repository woowacourse-teams/2024-corea, pull requests merged in 2024-08, with the labels that each got.

#194 Feat/#158: 피드백 카드 컴포넌트 추가
  frontend/package.json
  frontend/src/@types/NonEmptyArray.ts
  frontend/src/@types/feedback.ts
  frontend/src/components/feedback/evaluationPointBar/EvaluationPointBar.tsx
  frontend/src/components/feedback/feedbackCard/FeedbackCard.stories.tsx
  frontend/src/components/feedback/feedbackCard/FeedbackCard.style.ts
  frontend/src/components/feedback/feedbackCard/FeedbackCard.tsx
  frontend/src/components/shared/roomCardModal/RoomCardModalButton.tsx
Labels: FE, 기능

#199 [BE] 랭킹 페이지에 필요한 정보를 반환하는 기능 구현(#185)
  backend/src/main/java/corea/DataInitializer.java
  backend/src/main/java/corea/DemoDataInitializer.java
  backend/src/main/java/corea/domain/Ranking.java
  backend/src/main/java/corea/evaluation/domain/EvaluateClassification.java
  backend/src/main/java/corea/evaluation/domain/Evaluation.java
  backend/src/main/java/corea/profile/repository/ProfileRepository.java
  backend/src/main/java/corea/ranking/domain/Ranking.java
  backend/src/main/java/corea/ranking/dto/RankingResponse.java
  backend/src/main/java/corea/ranking/dto/RankingResponses.java
  backend/src/main/java/corea/ranking/repository/RankingRepository.java
  backend/src/main/java/corea/ranking/service/RankingService.java
  backend/src/main/java/corea/room/domain/Room.java
  backend/src/main/java/corea/room/domain/RoomClassification.java
  backend/src/main/java/corea/room/dto/RoomCreateRequest.java
  backend/src/main/java/corea/room/repository/RoomRepository.java
  backend/src/main/java/corea/room/service/RoomService.java
  backend/src/test/java/corea/fixture/MemberFixture.java
  backend/src/test/java/corea/fixture/RoomFixture.java
  backend/src/test/java/corea/profile/repository/ProfileRepositoryTest.java
  backend/src/test/java/corea/ranking/repository/RankingRepositoryTest.java
  backend/src/test/java/corea/ranking/service/RankingServiceTest.java
  backend/src/test/java/corea/room/repository/RoomRepositoryTest.java
  backend/src/test/java/corea/room/service/RoomServiceTest.java
Labels: BE, 기능

#305 [FE] 메인 페이지 배너 만들기(#298)
  frontend/src/assets/cloud.png
  frontend/src/components/common/header/Header.style.ts
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/layout/Layout.style.ts
  frontend/src/components/main/banner/Banner.style.ts
  frontend/src/components/main/banner/Banner.tsx
  frontend/src/components/main/banner/CyclingClasses.style.ts
  frontend/src/components/main/banner/CyclingClasses.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/styles/globalStyles.ts
Labels: FE, 디자인

#321 [FE] 방 상세 페이지 디자인 수정(#313)
  frontend/src/components/common/button/Button.style.ts
  frontend/src/components/common/button/Button.tsx
  frontend/src/components/common/iconRadioButton/IconRadioButton.style.ts
  frontend/src/components/common/label/Label.style.ts
  frontend/src/components/common/label/Label.tsx
  frontend/src/components/feedback/feedbackCard/FeedbackCard.style.ts
  frontend/src/components/feedback/feedbackForm/FeedbackForm.style.ts
  frontend/src/components/feedback/feedbackForm/RevieweeFeedbackForm.tsx
  frontend/src/components/feedback/feedbackForm/ReviewerFeedbackForm.tsx
  frontend/src/components/feedback/keywordOptionButton/KeywordOptionButton.style.ts
  frontend/src/components/feedback/keywordOptionButton/KeywordOptionButton.tsx
  frontend/src/components/feedback/revieweeFeedbackModal/RevieweeFeedbackModal.tsx
  frontend/src/components/feedback/reviewerFeedbackModal/ReviewerFeedbackModal.tsx
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.style.ts
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.tsx
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.style.ts
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.tsx
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.style.ts
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.tsx
  frontend/src/pages/roomDetail/RoomDetailPage.style.ts
  frontend/src/pages/roomDetail/RoomDetailPage.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
  frontend/src/utils/dateFormatter.ts
Labels: FE, 디자인

#331 [FE] 로딩, 에러, 로그인 페이지에 캐릭터 넣기(#297)
  frontend/public/fonts.css
  frontend/src/assets/default-character.png
  frontend/src/assets/error-character.png
  frontend/src/assets/happy-character.png
  frontend/src/assets/thinking-character.png
  frontend/src/components/common/Toast/Toast.style.ts
  frontend/src/components/common/button/Button.style.ts
  frontend/src/components/common/button/Button.tsx
  frontend/src/components/common/errorBoundary/Fallback.style.ts
  frontend/src/components/common/errorBoundary/Fallback.tsx
  frontend/src/components/common/errorBoundary/SentryApiErrorBoundary.tsx
  frontend/src/components/common/errorBoundary/SentryTotalBoundary.tsx
  frontend/src/components/layout/Layout.style.ts
  frontend/src/constants/message.ts
  frontend/src/hooks/mutations/useMutateAuth.ts
  frontend/src/pages/callback/CallbackPage.style.ts
  frontend/src/pages/callback/CallbackPage.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/theme.ts
Labels: FE, 디자인

#345 [FE] 전체적인 디자인 보완(#338)
  frontend/src/components/common/button/Button.style.ts
  frontend/src/components/common/errorBoundary/Fallback.tsx
  frontend/src/components/common/errorBoundary/SentryApiErrorBoundary.tsx
  frontend/src/components/common/errorBoundary/SentryTotalBoundary.tsx
  frontend/src/components/common/header/Header.style.ts
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/layout/Layout.style.ts
  frontend/src/components/main/banner/Banner.style.ts
  frontend/src/components/main/banner/Banner.tsx
  frontend/src/components/profile/profileCard/ProfileCard.style.ts
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.style.ts
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.tsx
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.style.ts
Labels: FE, 디자인
