Repository woowacourse-teams/2024-corea, pull requests merged in 2024-07, with the labels that each got.

#8 [BE] feat: 구현 도메인 정의 구현(#7)
  backend/src/main/java/corea/BackendApplication.java
  backend/src/main/java/corea/domain/Member.java
  backend/src/main/java/corea/domain/Room.java
  backend/src/test/java/corea/BackendApplicationTests.java
Labels: BE, 기능, 해커톤

#10 [BE] feat: 매칭 기능 구현(#6)
  backend/build.gradle
  backend/src/main/java/corea/member/domain/Matching.java
  backend/src/main/java/corea/member/entity/MatchedGroup.java
  backend/src/main/java/corea/member/repository/MatchedGroupRepository.java
  backend/src/main/java/corea/member/repository/MemberRepository.java
  backend/src/main/java/corea/member/service/MatchingService.java
  backend/src/test/java/corea/member/domain/MatchingTest.java
  backend/src/test/java/corea/member/service/MatchingServiceTest.java
Labels: BE, 기능, 해커톤

#14 [BE] refactor: 코드 리팩토링(#12)
  backend/src/main/java/corea/domain/Participation.java
  backend/src/main/java/corea/dto/JoinInfoResponse.java
  backend/src/main/java/corea/dto/ParticipationRequest.java
  backend/src/main/java/corea/dto/ParticipationResponse.java
  backend/src/main/java/corea/dto/RoomCreateRequest.java
  backend/src/main/java/corea/dto/RoomResponse.java
  backend/src/main/java/corea/member/domain/Matching.java
  backend/src/main/java/corea/member/repository/MemberRepository.java
  backend/src/main/java/corea/member/service/MatchingService.java
  backend/src/main/java/corea/repository/JoinInfoRepository.java
  backend/src/main/java/corea/repository/ParticipationRepository.java
  backend/src/main/java/corea/service/ParticipationService.java
  backend/src/main/java/corea/service/RoomService.java
  backend/src/test/java/corea/fixture/MemberFixture.java
  backend/src/test/java/corea/fixture/RoomFixture.java
  backend/src/test/java/corea/member/domain/MatchingTest.java
  backend/src/test/java/corea/member/service/MatchingServiceTest.java
  backend/src/test/java/corea/service/ParticipationServiceTest.java
  backend/src/test/java/corea/service/RoomServiceTest.java
Labels: BE, 리팩터링, 해커톤

#19 [BE] feat: 방 조회 API 구현(#12)
  backend/src/main/java/corea/cotroller/RoomController.java
  backend/src/main/java/corea/domain/Room.java
  backend/src/main/java/corea/dto/RoomCreateRequest.java
  backend/src/main/java/corea/dto/RoomResponse.java
  backend/src/main/java/corea/service/RoomService.java
  backend/src/test/java/corea/fixture/RoomFixture.java
  backend/src/test/java/corea/service/RoomServiceTest.java
Labels: BE, 기능, 해커톤

#20 [BE] feat: 리뷰이 / 리뷰어 조회 기능 구현 (#5)
  backend/src/main/java/corea/DataInitializer.java
  backend/src/main/java/corea/domain/Member.java
  backend/src/main/java/corea/dto/ApiResponse.java
  backend/src/main/java/corea/dto/MatchedGroupResponse.java
  backend/src/main/java/corea/member/controller/MemberController.java
  backend/src/main/java/corea/member/domain/Matching.java
  backend/src/main/java/corea/member/entity/MatchedGroup.java
  backend/src/main/java/corea/member/repository/MatchedGroupRepository.java
  backend/src/main/java/corea/member/service/MatchService.java
  backend/src/main/java/corea/member/service/MatchingService.java
  backend/src/main/java/corea/repository/MemberRepository.java
  backend/src/main/java/corea/repository/ParticipationRepository.java
Labels: BE, 기능, 해커톤

#21 [BE] config: CORS 설정 추가
  backend/src/main/java/corea/DataInitializer.java
  backend/src/main/java/corea/WebConfig.java
  backend/src/main/java/corea/room/RoomController.java
  backend/src/test/java/corea/fixture/MemberFixture.java
  backend/src/test/java/corea/member/domain/MatchingTest.java
  backend/src/test/java/corea/member/service/MatchingServiceTest.java
Labels: BE, 해커톤

#25 [FE] feat: 해커톤 기능 구현(#1)
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/jest.config.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/@types/icon.ts
  frontend/src/@types/reviewer.ts
  frontend/src/@types/roomInfo.ts
  frontend/src/App.tsx
  frontend/src/apis/apiClient.ts
  frontend/src/apis/endpoints.ts
  frontend/src/apis/my.api.ts
  frontend/src/apis/queryKeys.ts
  frontend/src/apis/rooms.api.ts
  frontend/src/assets/fonts/bmHanna.otf
  frontend/src/components/common/button/Button.style.ts
  frontend/src/components/common/button/Button.tsx
  frontend/src/components/common/contentForm/ContentForm.style.ts
  frontend/src/components/common/contentForm/ContentForm.tsx
  frontend/src/components/common/header/Header.style.ts
  frontend/src/components/common/header/Header.tsx
  frontend/src/components/common/icon/Icon.stories.tsx
  frontend/src/components/common/icon/Icon.tsx
  frontend/src/components/layout/Layout.style.ts
  frontend/src/components/layout/Layout.tsx
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.style.ts
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.tsx
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.style.ts
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.tsx
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.style.ts
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.tsx
  frontend/src/components/shared/roomCard/RoomCard.style.ts
  frontend/src/components/shared/roomCard/RoomCard.tsx
  frontend/src/components/shared/roomList/RoomList.style.ts
  frontend/src/components/shared/roomList/RoomList.tsx
  frontend/src/components/test.style.ts
  frontend/src/components/test.test.ts
  frontend/src/components/test2.tsx
  frontend/src/config/serverUrl.ts
  frontend/src/index.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/missionHandler.ts
  frontend/src/mocks/server.ts
  frontend/src/pages/main/MainPage.style.ts
  frontend/src/pages/main/MainPage.tsx
  frontend/src/pages/roomDetail/RoomDetailPage.style.ts
  frontend/src/pages/roomDetail/RoomDetailPage.tsx
  frontend/src/router.tsx
  frontend/src/styles/globalStyles.ts
  frontend/src/styles/style.d.ts
  frontend/src/styles/theme.ts
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: FE, 기능, 해커톤

#52 [FE] fix: 서버(테스트)환경에서 MSW 사용할 수 있도록 수정
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/my.api.ts
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.tsx
  frontend/src/components/shared/roomList/RoomList.tsx
  frontend/src/index.tsx
Labels: 수정, FE

#56 [BE] refactor: 도메인 수정 (#55)
  backend/src/main/java/corea/matching/domain/MatchResult.java
  backend/src/main/java/corea/member/domain/Member.java
Labels: BE, 리팩터링

#58 [BE] feat: 방 신청 구현(#32)
  backend/src/main/java/corea/WebConfig.java
  backend/src/main/java/corea/auth/RequestHandler.java
  backend/src/main/java/corea/auth/annotation/LoginUser.java
  backend/src/main/java/corea/auth/domain/AuthInfo.java
  backend/src/main/java/corea/auth/resolver/LoginMemberArgumentResolver.java
  backend/src/main/java/corea/exception/CoreaException.java
  backend/src/main/java/corea/exception/ExceptionResponseHandler.java
  backend/src/main/java/corea/exception/ExceptionType.java
  backend/src/main/java/corea/matching/controller/ParticipateController.java
  backend/src/main/java/corea/matching/controller/ParticipationControllerSpecification.java
  backend/src/main/java/corea/matching/repository/ParticipationRepository.java
  backend/src/main/java/corea/matching/service/ParticipationService.java
  backend/src/main/java/corea/room/controller/RoomController.java
  backend/src/main/java/corea/room/domain/Room.java
  backend/src/main/java/corea/room/dto/RoomResponse.java
  backend/src/main/java/corea/room/service/RoomService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/config/ControllerTest.java
  backend/src/test/java/config/TestExecutionListener.java
  backend/src/test/java/corea/fixture/MemberFixture.java
  backend/src/test/java/corea/fixture/RoomFixture.java
  backend/src/test/java/corea/matching/controller/ParticipateControllerTest.java
  backend/src/test/java/corea/matching/service/ParticipationServiceTest.java
Labels: BE, 기능

#54 [FE] config: 스토리북 배포 자동화 스크립트 설정(#53)
  frontend/package-lock.json
  frontend/package.json
Labels: FE

#60 [BE] feat: 유저가 참여중인 방 리스트 조회 기능 구현(#29)
  backend/src/main/java/corea/auth/annotation/LoginMember.java
  backend/src/main/java/corea/auth/domain/AuthInfo.java
  backend/src/main/java/corea/auth/resolver/LoginMemberArgumentResolver.java
  backend/src/main/java/corea/exception/CoreaException.java
  backend/src/main/java/corea/exception/ExceptionType.java
  backend/src/main/java/corea/matching/controller/ParticipateController.java
  backend/src/main/java/corea/matching/repository/ParticipationRepository.java
  backend/src/main/java/corea/room/controller/RoomController.java
  backend/src/main/java/corea/room/domain/Room.java
  backend/src/main/java/corea/room/dto/RoomCreateRequest.java
  backend/src/main/java/corea/room/dto/RoomResponse.java
  backend/src/main/java/corea/room/dto/RoomResponses.java
  backend/src/main/java/corea/room/service/RoomService.java
  backend/src/test/java/corea/room/acceptance/RoomAcceptanceTest.java
  backend/src/test/java/corea/room/fixture/MemberFixture.java
  backend/src/test/java/corea/room/fixture/RoomFixture.java
  backend/src/test/java/corea/room/service/RoomServiceTest.java
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/my.api.ts
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.tsx
  frontend/src/components/shared/roomList/RoomList.tsx
  frontend/src/index.tsx
Labels: BE, 기능

#63 [FE] fix: 누락된 파일 다시 추가(#62)
  frontend/jest.config.js
  frontend/jest.polyfills.js
  frontend/jest.setup.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/my.api.ts
  frontend/src/components/roomDetailPage/roomInfoCard/RoomInfoCard.tsx
  frontend/src/components/shared/roomList/RoomList.tsx
  frontend/src/index.tsx
Labels: 수정, FE

#64 [FE] feat: IconButton 공통 컴포넌트 만들기(#48)
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/iconButton/IconButton.stories.tsx
  frontend/src/components/common/iconButton/IconButton.style.ts
  frontend/src/components/common/iconButton/IconButton.tsx
Labels: 수정, FE, 기능

#61 [ALL] PR 템플릿 분리, CI 워크플로우 도입(#22)
  .github/PULL_REQUEST_TEMPLATE/all-issue-template.md
  .github/PULL_REQUEST_TEMPLATE/be-pull-request-template.md
  .github/PULL_REQUEST_TEMPLATE/fe-pull-request-template.md
  .github/workflows/backend-ci.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/storybook-cd.yml
Labels: ALL, 기능

#70 [BE] feat: 리뷰어/리뷰이 매칭 기능 구현 (#38)
  backend/src/main/java/corea/exception/ExceptionType.java
  backend/src/main/java/corea/matching/domain/MatchResult.java
  backend/src/main/java/corea/matching/domain/MatchingStrategy.java
  backend/src/main/java/corea/matching/domain/Pair.java
  backend/src/main/java/corea/matching/domain/PlainRandomMatching.java
  backend/src/main/java/corea/matching/domain/ReviewStatus.java
  backend/src/main/java/corea/matching/repository/MatchResultRepository.java
  backend/src/main/java/corea/matching/service/Matching.java
  backend/src/main/java/corea/member/service/MatchingService.java
  backend/src/test/java/corea/fixture/ParticipationFixture.java
  backend/src/test/java/corea/matching/domain/PlainRandomMatchingTest.java
  backend/src/test/java/corea/member/service/MatchingServiceTest.java
  backend/src/test/resources/clear.sql
Labels: BE, 기능

#77 [BE] refactor: 패키지 구조 수정 (#76)
  backend/src/main/java/corea/matching/service/MatchingService.java
  backend/src/main/java/corea/member/service/MatchService.java
  backend/src/test/java/corea/matching/service/MatchingServiceTest.java
Labels: BE, 리팩터링

#78 [BE] feat: 방 상세 정보 페이지 구현(#33, #36)
  backend/src/main/java/corea/DataInitializer.java
  backend/src/main/java/corea/auth/domain/AuthInfo.java
  backend/src/main/java/corea/auth/resolver/AccessedMemberArgumentResolver.java
  backend/src/main/java/corea/room/controller/RoomController.java
  backend/src/main/java/corea/room/domain/Room.java
  backend/src/main/java/corea/room/domain/RoomStatus.java
  backend/src/main/java/corea/room/dto/RoomCreateRequest.java
  backend/src/main/java/corea/room/dto/RoomResponse.java
  backend/src/main/java/corea/room/service/RoomService.java
  backend/src/main/java/corea/util/StringToListConverter.java
  backend/src/test/java/corea/fixture/RoomFixture.java
  backend/src/test/java/corea/room/fixture/MemberFixture.java
  backend/src/test/java/corea/room/fixture/RoomFixture.java
  backend/src/test/java/corea/util/StringToListConverterTest.java
Labels: BE, 기능

#59 [FE] test: MSW 핸들러 설정 추가(#57)
  frontend/src/apis/endpoints.ts
  frontend/src/mocks/browser.ts
  frontend/src/mocks/handler/missionHandler.ts
  frontend/src/mocks/handler/roomHandler.ts
  frontend/src/mocks/mockResponse/reviewInfo.json
  frontend/src/mocks/mockResponse/roomInfo.json
  frontend/src/mocks/mockResponse/roomInfos.json
  frontend/src/mocks/server.ts
Labels: 테스트, FE

#79 [FE] feat: 버튼 공통 컴포넌트 생성(#47)
  frontend/src/components/common/button/Button.stories.tsx
  frontend/src/components/common/button/Button.style.ts
  frontend/src/components/common/button/Button.tsx
  frontend/src/components/common/iconButton/IconButton.stories.tsx
  frontend/src/components/common/iconButton/IconButton.style.ts
  frontend/src/styles/globalStyles.ts
Labels: FE, 리팩터링, 기능, 디자인

#81 [FE] fix: 스토리북 액션 에러 해결(#80)
  .github/workflows/storybook-cd.yml
Labels: 수정, FE

#86 [FE] refactor: 레이아웃 title, content 컴포넌트 리팩토링(#41)
  frontend/src/components/common/contentForm/ContentForm.tsx
  frontend/src/components/common/contentSection/ContentSection.stories.tsx
  frontend/src/components/common/contentSection/ContentSection.style.ts
  frontend/src/components/common/contentSection/ContentSection.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/pages/roomDetail/RoomDetailPage.tsx
Labels: FE, 리팩터링, 기능

#82 [FE] feat: 공통 Label 컴포넌트 추가(#65)
  frontend/src/components/common/label/Label.stories.tsx
  frontend/src/components/common/label/Label.style.ts
  frontend/src/components/common/label/Label.tsx
Labels: FE, 기능, 디자인

#88 [FE] refactor: button 컴포넌트 적용(#87)
  frontend/src/components/roomDetailPage/myReviewee/MyReviewee.tsx
  frontend/src/components/roomDetailPage/myReviewer/MyReviewer.tsx
Labels: 수정, FE, 리팩터링

#89 [FE] fix: 스토리북 배포 문제 해결(#80)
  .github/workflows/storybook-cd.yml
Labels: 수정, FE

#91 [BE] 리뷰어, 리뷰이 조회 API 기능 구현 (#26, #34)
  backend/src/main/java/corea/matching/dto/MatchedGroupResponse.java
  backend/src/main/java/corea/matching/dto/ReviewInfo.java
  backend/src/main/java/corea/matching/dto/ReviewInfos.java
  backend/src/main/java/corea/matching/repository/MatchResultRepository.java
  backend/src/main/java/corea/matching/repository/MatchedGroupRepository.java
  backend/src/main/java/corea/matching/service/MatchResultService.java
  backend/src/main/java/corea/member/controller/MemberController.java
  backend/src/main/java/corea/member/entity/MatchedGroup.java
  backend/src/main/java/corea/member/service/MatchService.java
  backend/src/main/java/corea/room/controller/RoomController.java
  backend/src/main/java/corea/room/controller/RoomControllerSpecification.java
  backend/src/test/java/corea/matching/repository/MatchResultRepositoryTest.java
  backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
  backend/src/test/java/corea/matching/service/MatchingServiceTest.java
Labels: BE, 기능

#96 [BE] feat: 모집 완료된 방 리스트 API 구현(#31)
  backend/src/main/java/corea/DataInitializer.java
  backend/src/main/java/corea/auth/domain/AuthInfo.java
  backend/src/main/java/corea/auth/resolver/AccessedMemberArgumentResolver.java
  backend/src/main/java/corea/matching/dto/ReviewInfo.java
  backend/src/main/java/corea/member/domain/Member.java
  backend/src/main/java/corea/room/controller/RoomController.java
  backend/src/main/java/corea/room/controller/RoomControllerSpecification.java
  backend/src/main/java/corea/room/domain/Room.java
  backend/src/main/java/corea/room/dto/RoomResponse.java
  backend/src/main/java/corea/room/dto/RoomResponses.java
  backend/src/main/java/corea/room/service/RoomService.java
  backend/src/test/java/corea/matching/service/MatchResultServiceTest.java
  backend/src/test/java/corea/room/acceptance/RoomAcceptanceTest.java
  backend/src/test/java/corea/room/service/RoomServiceTest.java
  backend/src/test/java/corea/util/StringToListConverterTest.java
Labels: BE, 기능

#116 [FE] 헤더 디자인 변경(#83)
  frontend/src/apis/apiClient.ts
  frontend/src/components/common/header/Header.style.ts
  frontend/src/components/common/header/Header.tsx
Labels: FE, 디자인
